name:                less-arbitrary-benchmark
version:             0.1.0.0
github:              "githubuser/less-arbitrary-benchmark"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/less-arbitrary-benchmark#readme>

dependencies:
- base >= 4.7 && < 5
- testing-feat
- lazy-search
- hedgehog
- less-arbitrary
- QuickCheck
- criterion
# These are problematic:
#- gencheck
#- dragen

library:
  source-dirs: src

executables:
  less-arbitrary-benchmark-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - less-arbitrary-benchmark

tests:
  less-arbitrary-benchmark-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - less-arbitrary-benchmark
