name: less-arbitrary
version: '0.1.0.0'
category: Web
author: "Michał J. Gajda <mjgajda@migamake.com>"
maintainer: "Michał J. Gajda <mjgajda@migamake.com>"
license: BSD-3
extra-source-files:
- CHANGELOG.md
- README.md
dependencies:
- base
- containers
- text
- hspec
- QuickCheck
- unordered-containers
- hspec
- QuickCheck
- validity
- vector
- unordered-containers
- scientific
- genvalidity
- genvalidity-hspec
- genvalidity-property
- time
- email-validate
- generic-arbitrary
- mtl
- hashable
- random
- transformers
library:
  source-dirs: src
  exposed-modules:
  - Test.LessArbitrary
tests:
  less-arbitrary:
    main: LessArbitrary.hs
    source-dirs:
      - test/less/
      - test
    dependencies:
      - less-arbitrary

      - quickcheck-classes
      - quickcheck-instances
  #nonterminating:
  # main: Test/Arbitrary.hs
  # source-dirs:
  #   - test/nonterminating
  #   - test
  # dependencies:
  #   - less-arbitrary
  #   - quickcheck-classes
  #   - quickcheck-instances
        