name: union-types
version: '0.1.0.0'
category: Web
author: Michal J. Gajda
maintainer: mjgajda@migamake.com
license: BSD-3
extra-source-files:
- CHANGELOG.md
- README.md
dependencies:
- base
- aeson
- containers
- text
- hspec
- QuickCheck
- unordered-containers
- scientific
- hspec
- QuickCheck
- validity
- vector
- unordered-containers
- scientific
- validity
- genvalidity
- genvalidity-hspec
- genvalidity-property
- iso8601-time
- time
library:
  source-dirs: src
  exposed-modules:
  - Unions
tests:
  spec:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - union-types

